language: java
jdk:
- oraclejdk8
sudo: false
script: mvn clean verify
after_success:
- VERSION=`python -c "import xml.etree.ElementTree as ET;  print(ET.parse(open('pom.xml')).getroot().find('{http://maven.apache.org/POM/4.0.0}version').text)"`
- echo "Found version $VERSION"
- if [[ $VERSION == *-SNAPSHOT ]]; then echo "Deploying to OSSRH Snapshots..."; mvn
  clean deploy -DaltDeploymentRepository=ossrh::default::https://oss.sonatype.org/content/repositories/snapshots
  -DskipTests -B --settings .travis-deploy-settings.xml; else echo "Release version,
  deploy is manual."; fi
env:
  global:
  - secure: 0WSTeYsUGMvUhzUcPPlkeX4s9SJ348I5pdtVVd1HtGueIKXZX6qe3VzUGO7i/a1/XlIDCmZnUFZfRT9LnpFJzWS/9mfTpmObZJ0Z820jnWtkgmSDNxYSDQGEXQyEHsfqcfE7neaPXyEzT/eN5zAARfN75ZpQlmF6X++aLq0D4pTzJ6i9hLxPIkhbX1K00j/iBIPEMqbVkV7+oXLPFKpGX46mQeXpEE1yslKpZN4MDLSzTTvoQjFDi/BkeyEWCtQ1L0Kt/DgnzhaP+m6aYN0fkis63bjrkZWqN+PTC/gudj7OsDLPxVoeSIoa1b1qcbDA9A3OkX7PxWZkiLlrM4pbBdZckzECQV0Gt0DuA5ggu04X1YTd/YBuY2jKYHFNNnWnfK8LT/HaAA4DLNBScUeYyKDC28c/DH9o88TldWv0kVFTqPSzAkOalmIH/45vkTM7g2XIeCYLb0RLCbLt+ZgyDZV2d56W6BvwWHKIe8MfvH/D3LMjQM7cc7nBRVoBZVrzN1LIHncNezwAowksACOQHZV/gB7NgcG7gqXltHXE8w6gLzfEHlvdE4cwgEyj7qOgewyXOZEfukR022MUYED+QS8jnhgwNHXvXIDWR6Rhff/M4pQlau2LsIX7b8iDv07g38N2OjpcJqF8SbbY17UggKI9Vn7yTMVgGY17awQj6i0=
  - secure: bPp0EeACnvYU+55EMgdsSF+RxdwiQ+4aA57fZml78p4sFUhOq6u1oObUDWjMXNs5q9ZIZJc4iqEk6pWISEJ6GrwyWpw/3IG2y6slIrbfO/dl8coB2tA8/xNPb4+NTfYTK/ie20RliDFAtkfIiUkzRazVeUIziDXJqaXY2RjboI2wcCsEbPl3368zib7XG2v85V4mFb+clq0zAGL0AC4yTRp7btbMkCKzJrO7/VHnoSXpFeI9Lh1N5r/+xveOmEJptr/xZ+heIFre5Ob/IaAbDnuh87ejpRGsYapnwl6OIJbSdSFoSqLXFPg/7Zmp2Gn97ETMTlN0hYFgOc/DR+QvY1XIRl8iuoNJAilCzueeuXZijf7DEu+ZSoI2YXqYzSxXbtpIMtXVyBrfjpWHPDM/AUG/XD2F01vSF5lYXX91x1JtOs+R7PHjxUqMHzJeThOatPv0q4H4dNpQ1xOAN6ROclHnsXQnM7TlN/wu/iXaDCbEh1NVGDHk06XA0bALzEV7MSWEsL78bIh8OZV5NnS7b83Q0dwtuns75hUw5KV+vjpT18JKi1dDJvPWRBS7HWJHATM94m8htcdWZsjPCv/ekyhn1nYRKejc1gFapX/UYEDvclyy5SIT1DQFJBpxOLqXqw4iHd0ztZGGJFu6YcaFvStLaJibSm+PaS6qlxbqjas=
